import { createAction } from '@reduxjs/toolkit';

export const ACTION_TYPES = {
  TRANSACTION_CREATE_REQUEST: 'TRANSACTION_CREATE_REQUEST',
  TRANSACTION_CREATE_SUCCESS: 'TRANSACTION_CREATE_SUCCESS',
  TRANSACTION_CREATE_FAIL: 'TRANSACTIONS_REASSIGN',
  TRANSACTION_UPDATE_REQUEST: 'TRANSACTION_UPDATE_REQUEST',
  TRANSACTION_UPDATE_SUCCESS: 'TRANSACTION_UPDATE_SUCCESS',
  TRANSACTION_UPDATE_FAIL: 'TRANSACTION_UPDATE_FAIL',
  TRANSACTION_DELETE_REQUEST: 'TRANSACTION_DETELE_REQUEST',
  TRANSACTION_DELETE_SUCCESS: 'TRANSACTION_DETELE_SUCCESS',
  TRANSACTION_DELETE_FAIL: 'TRANSACTION_DETELE_FAIL',
  TRANSACTIONS_REASSIGN_REQUEST: 'TRANSACTIONS_REASSIGN_REQUEST',
  TRANSACTIONS_REASSIGN_SUCCESS: 'TRANSACTIONS_REASSIGN_SUCCESS',
  TRANSACTIONS_REASSIGN_FAIL: 'TRANSACTIONS_REASSIGN_FAIL',
  TRANSACTIONS_PULL_BANKING_REQUEST: 'TRANSACTIONS_PULL_BANKING_REQUEST',
  TRANSACTIONS_CREATE_MANY_REQUEST: 'TRANSACTIONS_CREATE_MANY_REQUEST',
  TRANSACTIONS_CREATE_MANY_SUCCESS: 'TRANSACTIONS_CREATE_MANY_SUCCESS',
  TRANSACTIONS_CREATE_MANY_FAIL: 'TRANSACTIONS_CREATE_MANY_FAIL',
  TRANSACTIONS_LOAD_REQUEST: 'TRANSACTIONS_LOAD_REQUEST',
  TRANSACTIONS_LOAD_SUCCESS: 'TRANSACTIONS_LOAD_SUCCESS',
  TRANSACTIONS_LOAD_FAIL: 'TRANSACTIONS_LOAD_FAIL',
};

export const createTransaction = createAction(
  ACTION_TYPES.TRANSACTION_CREATE_REQUEST
);
export const createTransactionSuccess = createAction(
  ACTION_TYPES.TRANSACTION_CREATE_SUCCESS
);
export const createTransactionFail = createAction(
  ACTION_TYPES.TRANSACTION_CREATE_FAIL
);
export const transactionsReassign = createAction(
  ACTION_TYPES.TRANSACTIONS_REASSIGN_REQUEST
);
export const transactionsReassignSuccess = createAction(
  ACTION_TYPES.TRANSACTIONS_REASSIGN_SUCCESS
);
export const transactionsReassignFail = createAction(
  ACTION_TYPES.TRANSACTIONS_REASSIGN_FAIL
);
export const transactionsPullBanking = createAction(
  ACTION_TYPES.TRANSACTIONS_PULL_BANKING_REQUEST
);
export const transactionsCreateMany = createAction(
  ACTION_TYPES.TRANSACTIONS_CREATE_MANY_REQUEST
);
export const transactionsCreateManySuccess = createAction(
  ACTION_TYPES.TRANSACTIONS_CREATE_MANY_SUCCESS
);
export const transactionsCreateManyFail = createAction(
  ACTION_TYPES.TRANSACTIONS_CREATE_MANY_FAIL
);
export const updateTransaction = createAction(
  ACTION_TYPES.TRANSACTION_UPDATE_REQUEST
);
export const updateTransactionSuccess = createAction(
  ACTION_TYPES.TRANSACTION_UPDATE_SUCCESS
);
export const updateTransactionFail = createAction(
  ACTION_TYPES.TRANSACTION_UPDATE_FAIL
);
export const loadTransactions = createAction(
  ACTION_TYPES.TRANSACTIONS_LOAD_REQUEST
);
export const loadTransactionsSuccess = createAction(
  ACTION_TYPES.TRANSACTIONS_LOAD_SUCCESS
);
export const loadTransactionsFail = createAction(
  ACTION_TYPES.TRANSACTIONS_LOAD_FAIL
);

export const deleteTransaction = createAction(
  ACTION_TYPES.TRANSACTION_DELETE_REQUEST
);
export const deleteTransactionSuccess = createAction(
  ACTION_TYPES.TRANSACTION_DELETE_SUCCESS
);
export const deleteTransactionFail = createAction(
  ACTION_TYPES.TRANSACTION_DELETE_FAIL
);
